url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Robert Wildgoose" # the name of your site, e.g. ACME Corp.
copyright: "Copyright &copy; Robert Wildgoose"
twitter: "https://www.twitter.com/hewhoiscould"
apple: "https://apps.apple.com/bh/developer/robert-wildgoose/id1469132514"
linkedIn: "https://www.linkedin.com/in/robert-wildgoose-2031a183/"
github: "https://github.com/RobertWildgoose"
jobTitle: "Senior Mobile Apps Developer"
collections:
  - iphone_apps
  - mac_apps
  - innovation