# Site settings
title: Robert Wildgoose
email: contact@robertwildgoose.co.uk
url: https://robertwildgoose.github.io/
skills: "Mobile App Developer"
meta_author: Wildgoose Robert

collections:
  projects:
    output: true
  nugets:
    output: true
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0d355d #0d355d
  secondary: 477cb1 #477cb1
  secondary-dark: 247cd4 #031425

# Footer settings
footer:
  copyright: Robert Wildgoose

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/robert-wildgoose-2031a183/
  - title: facebook
    url: https://www.facebook.com/robert.wildgoose.10
  - title: stack-overflow
    url: https://stackoverflow.com/users/10173290/rwildgoose
  - title: github
    url: https://github.com/RobertWildgoose


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
