title: "Robert Wildgoose"
email: contact@robertwildgoose.co.uk
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Robert
paginate: 30
locale: en_gb
lang:  en_gb
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-RQF22W79RR

# Social
social:
  linkedin: https://www.linkedin.com/in/robert-wildgoose-2031a183/
  github: https://github.com/RobertWildgoose

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives